namespace SLB.WellMaps.Configs
{
    public static class ColorScheme
    {
        /* Palette generated by Material Palette - materialpalette.com/light-blue/red */

        public readonly static string primary           = "#03A9F4";
        public readonly static string primary_dark      = "#0288D1";
        public readonly static string primary_light     = "#B3E5FC";
        public readonly static string accent            = "#FF5252";
        public readonly static string primary_text      = "#212121";
        public readonly static string secondary_text    = "#727272";
        public readonly static string text              = "#FFFFFF";
        public readonly static string divider           = "#B6B6B6";
    }
}
